version: "3.9"

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
  way:
    build: .
    image: airplane-docker
    container_name: airplane_app
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
volumes:
  data: {}